name: 'build docker images: mqtt-board'

on:
  #push:
  #  branches:
  #    - 'main'
  #    - 'master'
  #  paths:
  #    - 'mqtt-board.multiarch.alpine.Dockerfile'
  #    - '.github/workflows/build_docker_images-mqtt-board.yaml'
  workflow_dispatch:
  schedule:
    - cron: '50 5 27 * *'  # At 05:50 on day-of-month 27.

defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shell-Script
        id: script
        run: |
          BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          BUILD_DATE_NUMERIC="${BUILD_DATE//[^[:digit:]]/}"
          COMMIT_HASH=${GITHUB_SHA::7}
          GITHUB_REPO=${GITHUB_REPOSITORY,,}
          GITHUB_REPO_SHORT=${GITHUB_REPO#*/}
          GITHUB_REPO_SHORT=${GITHUB_REPO_SHORT#"docker-"}
          DOCKER_REPO=${{ secrets.DOCKER_USERNAME }}/${GITHUB_REPO_SHORT}
          REDHAT_QUAY_REPO=${{ secrets.REDHAT_QUAY_USERNAME }}/${GITHUB_REPO_SHORT}
          
          # Set output parameters to action.
          echo "build_date=${BUILD_DATE}" >> "$GITHUB_OUTPUT"
          echo "build_date_numeric=${BUILD_DATE_NUMERIC}" >> "$GITHUB_OUTPUT"
          echo "commit_hash=${COMMIT_HASH}" >> "$GITHUB_OUTPUT"
          echo "github_repo=${GITHUB_REPO}" >> "$GITHUB_OUTPUT"
          echo "docker_repo=${DOCKER_REPO}" >> "$GITHUB_OUTPUT"
          echo "redhat_quay_repo=${REDHAT_QUAY_REPO}" >> "$GITHUB_OUTPUT"

          # mqtt-board
          VERSION=$(wget -qO- https://api.github.com/repos/flespi-software/MQTT-Board/tags | grep 'name' | cut -d\" -f4 | head -1)
          echo "VERSION=${VERSION}"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub 
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to RED HAT Quay.io Container Registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.REDHAT_QUAY_USERNAME }}
          password: ${{ secrets.REDHAT_QUAY_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./mqtt-board.multiarch.alpine.Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          build-args: |
            BUILD_DATE=${{steps.script.outputs.build_date}}
            VCS_REF=${{steps.script.outputs.commit_hash}}
            VERSION=${{steps.script.outputs.version}}
          tags: |
            docker.io/${{steps.script.outputs.docker_repo}}:mqtt-board
            quay.io/${{steps.script.outputs.redhat_quay_repo}}:mqtt-board
            ghcr.io/${{steps.script.outputs.github_repo}}:mqtt-board
          #  ghcr.io/${{steps.script.outputs.github_repo}}:mqtt-board-${{steps.script.outputs.version}}
          #  ghcr.io/${{steps.script.outputs.github_repo}}:mqtt-board-${{steps.script.outputs.build_date_numeric}}.${{steps.script.outputs.commit_hash}}
